### ISSUE TITLE
Atualização n8n

### ISSUE THREAD

**Issue by victorllgarcia** [soumatheusgomes/n8n-setup#1]
Olá! Muito obrigado pelo projeto, facilitou muito a vida de todos! Apenas uma dúvida: Como fazer para atualizar? Já tentei subir várias vezes o container e ele não está puxando as versões mais recentes do projeto n8n. Poderia ajudar? Obrigado!

**Comment by hugorn** [comment]
Aqui pra mim sempre atualiza quando vou dentro da pasta de instalação e executo ./update.sh
Pode conferir o código aqui
https://github.com/soumatheusgomes/n8n-setup/blob/main/update.sh

**Comment by victorllgarcia** [comment]
> Aqui pra mim sempre atualiza quando vou dentro da pasta de instalação e executo ./update.sh Pode conferir o código aqui https://github.com/soumatheusgomes/n8n-setup/blob/main/update.sh

Muito obrigado pela resposta rápida! Eu não entendo muito sobre os códigos - apenas vou tentando me virar. Eu acho que de onde ele está puxando a imagem está faltando atualizar talvez. Mesmo executando o arquivo de atualização ele ainda assim indica que existem versões novas. Alguma idéia? 

![CleanShot 2024-08-18 at 14 32 09](https://github.com/user-attachments/assets/9c825c7b-d116-490f-9174-ab28dc015cfc)

**Comment by hugorn** [comment]
Nesse site (https://docs.n8n.io/release-notes/)  você consegue ver a versão Latest e a Versão Next que digamos que é a Beta e não é recomendado colocar em produção, aqui no docker hub você consegue ver a a imagem já está disponível para deploy: https://hub.docker.com/r/n8nio/n8n/tags
Atualizei o meu hoje e está na última versão estável que é a 1.54.4
![image](https://github.com/user-attachments/assets/1370813f-ad90-45e8-9a88-411f19b2e8bf)

**Comment by victorllgarcia** [comment]
Muitíssimo obrigado pela ajuda novamente! E desculpe o incomodo. Seus vídeos estão ótimo no YouTube! Espero que volte a fazer mais vídeos em breve. Aqui atualizou agora realmente também

> Nesse site (https://docs.n8n.io/release-notes/) você consegue ver a versão Latest e a Versão Next que digamos que é a Beta e não é recomendado colocar em produção, aqui no docker hub você consegue ver a a imagem já está disponível para deploy: https://hub.docker.com/r/n8nio/n8n/tags Atualizei o meu hoje e está na última versão estável que é a 1.54.4 ![image](https://private-user-images.githubusercontent.com/9035153/359078453-1370813f-ad90-45e8-9a88-411f19b2e8bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTg0NTMsIm5iZiI6MTcyNDA5ODE1MywicGF0aCI6Ii85MDM1MTUzLzM1OTA3ODQ1My0xMzcwODEzZi1hZDkwLTQ1ZTgtOWE4OC00MTFmMTliMmU4YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMjAwOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUwYTk4YmYxNjI4ZDk5ZGM4NmI1ODcxMzNhNDk3MzBiNDBjYTY1NjA1NjdlOTQzYTgwMjdiMzk2NTRiNzI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O7bB0cehcIdCDUOfe63anRXtHvuI18iYqm5-VGWrVDQ)

**Comment by hugorn** [comment]
Não tem o que agradecer, e só pra constar eu não sou o rapaz do vídeo, estou apenas ajudando porque graças a esse repositório também consegui fazer o meu n8n funcionar redondinho. Estou aqui pra agradecer também!

**Comment by victorllgarcia** [comment]
> Não tem o que agradecer, e só pra constar eu não sou o rapaz do vídeo, estou apenas ajudando porque graças a esse repositório também consegui fazer o meu n8n funcionar redondinho. Estou aqui pra agradecer também!

Neste caso te agradeço mais ainda pela gentileza! Obrigado por sair do seu caminho para vir responder a dúvida. Agora que instalei apropriadamente preciso apenas encontrar locais para aprender mais sobre o sistema. Meu intuito inicial era jogar a lista de clientes (pacientes) de uma plataforma para um CRM, enfim. Te agradeço pela ajuda

**Comment by al4nzera** [comment]
Guys I need help.
I installed n8n on a digital ocean server, everything worked fine, but I tried to get the newest version and when I went up to the server my n8n no longer opened. I destroyed this server and uploaded another one, but now when I upload another server, n8n stays active for about 2 hours and then I can't log in anymore, it stays on the screenshot I posted below. I've uploaded several servers and they all give the same error, can anyone help me? [I'm still a beginner at programming].

![Screenshot_3](https://github.com/user-attachments/assets/3b490cbc-95c8-4689-b202-ffd093e9ff65)

**Comment by al4nzera** [comment]
kkkkkkkkkkkkkkkkkkkk aqui so tem br

Pessoal preciso de ajuda.
Instalei o n8n em um servidor digital ocean, tinha dado tudo certo porem tentei pegar a versão mais nova e quando subi pro servidor meu n8n não abriu mais. Destrui esse servidor e subi outro porém agora quando subo outro servidor o n8n fica cerca de 2h ativo e depois não consigo mais entrar, fica na tela do print que coloquei abaixo. Já subi vários servidores e todos dão esse mesmo erro alguem consegue me ajudar ? [ainda sou iniciante em programação]

**Comment by hugorn** [comment]
Fala @al4nzera 
O que pode estar ocorrendo é sua instalação estar ao longo do tempo estar topando a memória por algum motivo, consegue monitorar o uso de ram dele como está?

**Comment by al4nzera** [comment]
Fala @hugorn, muito obrigado por me responder irmão
Cara como falei sou iniciante em programação, essa memória que você falou seria do domínio DNS ou o do próprio servidor ?

**Comment by al4nzera** [comment]
Se for do servidor está tranquilo, o que acontece eu subi e destrui vários servidores porem todos eu colocava o mesmo domínio para acessar o n8n, tanto que quando subo um servidor novo com esse domínio que utilizo ele nem entra no aplicativo sabe? Já tentei de tudo, troquei o domínio e consegui acessar o n8n porém ele vem todo bugado.
EX: quando faço requisição de webhook com mensagem, preciso enviar várias pra ele puxar os dados e ativar o webhook

**Comment by al4nzera** [comment]
Resumo da obra, fiz vários testes tentando aprender e agora pelo jeito consegui bugar tanto meu domínio quanto o aplicativo que eu instalo :( kkkkkkkk loucura mano acho que consegui explicar o que está rolando.

**Comment by victorllgarcia** [comment]
> > Aqui pra mim sempre atualiza quando vou dentro da pasta de instalação e executo ./update.sh Pode conferir o código aqui https://github.com/soumatheusgomes/n8n-setup/blob/main/update.sh
> 
> Muito obrigado pela resposta rápida! Eu não entendo muito sobre os códigos - apenas vou tentando me virar. Eu acho que de onde ele está puxando a imagem está faltando atualizar talvez. Mesmo executando o arquivo de atualização ele ainda assim indica que existem versões novas. Alguma idéia?
> 
> ![CleanShot 2024-08-18 at 14 32 09](https://private-user-images.githubusercontent.com/109931022/358925820-9c825c7b-d116-490f-9174-ab28dc015cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjI4NjcsIm5iZiI6MTcyNzc2MjU2NywicGF0aCI6Ii8xMDk5MzEwMjIvMzU4OTI1ODIwLTljODI1YzdiLWQxMTYtNDkwZi05MTc0LWFiMjhkYzAxNWNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNjAyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmFkMDMwNTM1MzU0ZWM0NTE3MzkzOGIyMjk1Y2QzMDJkZGQ2MDk3ZjEwZWM0MTRlNGZjZWYwZjk5YjZhZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dX6irhXoYfC9o-7tOYede4-AxKmqueq0HwLhvhQ56X0)

**Gostaria de deixar um pequeno alerta:** O motivo de não estar atualizando de forma alguma anteriormente era por que eu havia liberado no firewall apenas a porta do n8n (5678). Certifique-se de liberar também as outras (Postgres, Browserless, redis) -> 5432, 3000 e 6379. Era esse o erro. Notei hoje após vários dias "sem chegar" a atualização. Depois de liberar o firewall tudo passou a funcionar 100% direito e atualizado
